version: '3'

services:
  php-fpm:
    build:
      context: './php-fpm'
    volumes:
       - ../:/var/www
  nginx:
    build: 
      context: './nginx'
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
    depends_on:
      - php-fpm